const defaultProducts = [
  {
    id: 1,
    category: 'smartphones',
    name: 'Samsung Galaxy S24 Ultra',
    desc: '5G, 256GB Storage, AI Camera & S-Pen included',
    price: 124999,
    originalPrice: '₹1,39,999',
    rating: 5,
    src: 'media/sam.webp',
    badge: 'Best Seller',
    stock: 15
  },
  {
    id: 2,
    category: 'smartphones',
    name: 'Nova 2 Neo 5G',
    desc: '6000mAh Battery, 48MP Dual Sony Camera',
    price: 12999,
    originalPrice: '₹17,999',
    rating: 4,
    src: 'media/-original-imahgeusscuw8ezf.webp',
    badge: 'Special Deal',
    stock: 20
  },
  {
    id: 3,
    category: 'laptops',
    name: 'Lenovo Legion Pro 5',
    desc: 'AMD Ryzen 7, RTX 4060, 16GB RAM, 1TB SSD',
    price: 144999,
    originalPrice: '₹1,69,999',
    rating: 5,
    src: 'media/legion.webp',
    badge: 'Gaming',
    stock: 10
  },
  {
    id: 4,
    category: 'laptops',
    name: 'Lenovo ThinkPad E14',
    desc: 'Intel Core i5, 8GB RAM, 512GB SSD, Windows 11',
    price: 56999,
    originalPrice: '₹72,000',
    rating: 4,
    src: 'media/lenvo.webp',
    badge: 'Business',
    stock: 12
  },
  {
    id: 5,
    category: 'audio',
    name: 'Mivi Soundbar 100W',
    desc: 'Deep Bass Home Theater, 2.1 Channel Cinema Sound',
    price: 3999,
    originalPrice: '₹7,999',
    rating: 4,
    src: 'media/mivi.webp',
    badge: '50% OFF',
    stock: 25
  },
  {
    id: 6,
    category: 'audio',
    name: 'Buds Pro Gen 2',
    desc: 'Active Noise Cancellation, 40 Hours Playback',
    price: 999,
    originalPrice: '₹1,999',
    rating: 4,
    src: 'media/bud.webp',
    badge: 'Trending',
    stock: 50
  },
  {
    id: 7,
    category: 'audio',
    name: 'Ex Wireless ANC Earbuds',
    desc: 'True Wireless Audio with Smart Touch controls',
    price: 1299,
    originalPrice: '₹2,999',
    rating: 4,
    src: 'media/ex.webp',
    badge: 'Popular',
    stock: 30
  },
  {
    id: 8,
    category: 'smartwatches',
    name: 'Plex Smart Watch Active',
    desc: 'Heart rate tracker, SpO2 sensor, Sleep analytics',
    price: 2499,
    originalPrice: '₹4,999',
    rating: 5,
    src: 'media/plex.webp',
    badge: 'New Launch',
    stock: 40
  },
  {
    id: 9,
    category: 'tvs',
    name: 'Sony Bravia 55" 4K Smart TV',
    desc: 'Google TV, Dolby Vision HDR, X1 Processor',
    price: 57999,
    originalPrice: '₹74,900',
    rating: 5,
    src: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=500&auto=format&fit=crop&q=60',
    badge: '4K Ultra',
    stock: 8
  },
  {
    id: 10,
    category: 'gaming',
    name: 'PlayStation 5 Console Slim',
    desc: '825GB SSD, DualSense Wireless Controller',
    price: 44990,
    originalPrice: '₹54,990',
    rating: 5,
    src: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500&auto=format&fit=crop&q=60',
    badge: 'Hot Seller',
    stock: 15
  },
  {
    id: 11,
    category: 'appliances',
    name: 'Dyson V15 Vacuum Cleaner',
    desc: 'Laser dust detection, High torque cleaner head',
    price: 65900,
    originalPrice: '₹72,900',
    rating: 4,
    src: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500&auto=format&fit=crop&q=60',
    badge: 'Premium',
    stock: 5
  },
  {
    id: 12,
    category: 'cameras',
    name: 'Sony Alpha 7 IV Mirrorless',
    desc: '33MP Full-Frame sensor, 4K 60p video recording',
    price: 218990,
    originalPrice: '₹2,42,900',
    rating: 5,
    src: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60',
    badge: 'Pro Choice',
    stock: 6
  },
  {
    id: 13,
    category: 'accessories',
    name: 'Logitech MX Master 3S Mouse',
    desc: 'Ergonomic silent mouse, 8K DPI tracking',
    price: 9495,
    originalPrice: '₹10,995',
    rating: 5,
    src: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&auto=format&fit=crop&q=60',
    badge: 'Workplace',
    stock: 18
  },
  {
    id: 14,
    category: 'monitors',
    name: 'Zonda UltraWide 34" Curved',
    desc: 'WQHD Display, 144Hz refresh rate, HDR10',
    price: 29999,
    originalPrice: '₹45,000',
    rating: 4,
    src: 'media/tab.webp',
    badge: 'Curved',
    stock: 7
  },
  {
    id: 15,
    category: 'audio',
    name: 'Zonda Luxury Perfume',
    desc: 'An exquisite French fragrance elixir blending cedarwood and amber.',
    price: 1499,
    originalPrice: '₹2,499',
    rating: 5,
    src: 'media/per.webp',
    badge: 'Trending',
    stock: 20
  }
];

module.exports = defaultProducts;
